"""empty message

Revision ID: 141b8c87fe7d
Revises: 7131b20947de
Create Date: 2024-08-31 13:32:13.214127

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv('FLASK_ENV')
SCHEMA = os.environ.get('SCHEMA')


# revision identifiers, used by Alembic.
revision = '141b8c87fe7d'
down_revision = '7131b20947de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legalities', sa.JSON(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('mana_cost', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('set_abr', sa.String(), nullable=True),
    sa.Column('set_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == 'production':
        op.execute(f'ALTER TABLE users SET SCHEMA {SCHEMA};')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decks')
    op.drop_table('cards')
    # ### end Alembic commands ###
