"""update card model

Revision ID: 7f558702f736
Revises: d7b50e987815
Create Date: 2024-09-10 15:32:00.566072

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '7f558702f736'
down_revision = 'd7b50e987815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scryfall_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('tcgplayer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('oracle_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('colors', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mana_cost', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('power', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('toughness', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rarity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('artist', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('artist_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('illustration_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('set_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('set_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('set_id', sa.Uuid(), nullable=True))
        batch_op.create_unique_constraint('uniq_oracle', ['oracle_id'])
        batch_op.create_unique_constraint('uniq_tcgplayer', ['tcgplayer_id'])
        batch_op.create_unique_constraint('uniq_scryfall', ['scryfall_id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint('uniq_oracle', type_='unique')
        batch_op.drop_constraint('uniq_tcgplayer', type_='unique')
        batch_op.drop_constraint('uniq_scryfall', type_='unique')
        batch_op.drop_column('set_id')
        batch_op.drop_column('set_name')
        batch_op.drop_column('set_code')
        batch_op.drop_column('illustration_id')
        batch_op.drop_column('artist_id')
        batch_op.drop_column('artist')
        batch_op.drop_column('rarity')
        batch_op.drop_column('toughness')
        batch_op.drop_column('power')
        batch_op.drop_column('keywords')
        batch_op.drop_column('mana_cost')
        batch_op.drop_column('colors')
        batch_op.drop_column('oracle_id')
        batch_op.drop_column('tcgplayer_id')
        batch_op.drop_column('scryfall_id')

    # ### end Alembic commands ###
